# spring:
#   datasource:
#     url: jdbc:h2:mem:hello
#     username: sa
#     password: password
#     driver-class-name: org.h2.Driver  
# spring:
#   jpa:
#     generate-ddl: true
#     hibernate:
#       ddl-auto: create
#     defer-datasource-initialization: true