INSERT INTO CUSTOMER VALUES (1, 'Karthik');
INSERT INTO CUSTOMER VALUES (2, 'Avyukt');
INSERT INTO CUSTOMER VALUES (3, 'Ashwat');
INSERT INTO CUSTOMER VALUES (4, 'Srividya');

INSERT INTO GIFT (NAME) VALUES ('Toy');
INSERT INTO GIFT (NAME) VALUES ('Book');
INSERT INTO GIFT (NAME) VALUES ('Cash');
INSERT INTO GIFT (NAME) VALUES ('Gold');
INSERT INTO GIFT (NAME) VALUES ('Perfume');

INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (2, 1);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (3, 1);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (4, 3);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (4, 4);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (4, 4);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (4, 2);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (1, 3);
INSERT INTO CUSTOMER_GIFTS (CUSTOMER_ID, GIFT_ID) VALUES (1, 5);