CREATE TABLE GIFT (ID SERIAL PRIMARY KEY, NAME VARCHAR(200));
CREATE TABLE CUSTOMER (ID INTEGER PRIMARY KEY, NAME VARCHAR(200));
CREATE TABLE CUSTOMER_GIFTS (
    ID IDENTITY NOT NULL PRIMARY KEY,
    CUSTOMER_ID INTEGER, 
    GIFT_ID INTEGER, 
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID) ,
    CONSTRAINT FK_GIFT_ID FOREIGN KEY (GIFT_ID) REFERENCES GIFT (ID)
);